"""Pydantic schemas for the Audio Authenticity Intelligence Engine.

These models define the request and response contracts for the
POST /analyze-audio endpoint. They do NOT modify any existing models.
"""

from pydantic import BaseModel, Field


class TranscriptAnalysis(BaseModel):
    """Trust intelligence results derived from the audio transcript."""

    trust_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Rule-based + Gemini hybrid trust score for the transcript (0-100)",
        examples=[91],
    )
    risk_level: str = Field(
        ...,
        description="Risk tier derived from trust score: Low / Medium / High",
        examples=["Low"],
    )
    ai_generated_probability: int = Field(
        ...,
        ge=0,
        le=100,
        description="Estimated probability (0-100) the transcript text was AI-generated",
        examples=[73],
    )


class AudioAnalysisResponse(BaseModel):
    """Full response from the Audio Authenticity Intelligence Engine."""

    audio_ai_probability: int = Field(
        ...,
        ge=0,
        le=100,
        description=(
            "Probability (0-100) that the audio was generated by an AI/TTS system. "
            "0-30 = Likely Human, 31-69 = Uncertain, 70-100 = Likely AI Generated."
        ),
        examples=[82],
    )
    classification: str = Field(
        ...,
        description="Human-readable classification label",
        examples=["Likely AI Generated"],
    )
    confidence: str = Field(
        ...,
        description="Confidence tier for the classification: Low / Medium / High",
        examples=["High"],
    )
    audio_indicators: list[str] = Field(
        default_factory=list,
        description="Detected acoustic/prosodic indicators driving the classification",
        examples=[["Low pitch variation", "Uniform pacing", "Synthetic prosody"]],
    )
    transcript: str = Field(
        ...,
        description="Full speech-to-text transcript of the uploaded audio",
        examples=["Welcome to Technoax. This is an automated demonstration."],
    )
    transcript_analysis: TranscriptAnalysis = Field(
        ...,
        description="Trust intelligence analysis applied to the transcript text",
    )
    audio_explanation: str = Field(
        ...,
        description=(
            "Detailed AI-generated explanation of why the audio was classified "
            "as human, AI-generated, or uncertain."
        ),
        examples=[
            "The audio demonstrates characteristics commonly associated with synthetic "
            "speech including consistent energy distribution, minimal breathing artifacts, "
            "and highly regular pacing."
        ],
    )
